<?php
declare(strict_types=1);

require __DIR__ . '/../../public-hostinger/kush-kings-chess/api/chess-rules.php';

function kkc_test_equal(mixed $actual, mixed $expected, string $label): void
{
    if ($actual !== $expected) {
        fwrite(STDERR, "FAIL: {$label}\nExpected: " . var_export($expected, true) . "\nActual: " . var_export($actual, true) . "\n");
        exit(1);
    }
    fwrite(STDOUT, "PASS: {$label}\n");
}

function kkc_test_illegal(string $fen, string $from, string $to, ?string $promotion, string $label): void
{
    $failed = false;
    try {
        kkc_chess_apply_move($fen, $from, $to, $promotion);
    } catch (InvalidArgumentException $err) {
        $failed = true;
    }
    kkc_test_equal($failed, true, $label);
}

$start = 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1';
$state = kkc_chess_parse_fen($start);
kkc_test_equal(count(kkc_chess_legal_moves($state)), 20, 'initial position exposes 20 legal moves');

$e4 = kkc_chess_apply_move($start, 'e2', 'e4');
kkc_test_equal($e4['fen'], 'rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq e3 0 1', 'server derives the FEN after e4');
kkc_test_equal($e4['san'], 'e4', 'server derives SAN for e4');

$e5 = kkc_chess_apply_move($e4['fen'], 'e7', 'e5');
kkc_test_equal($e5['fen'], 'rnbqkbnr/pppp1ppp/8/4p3/4P3/8/PPPP1PPP/RNBQKBNR w KQkq e6 0 2', 'server derives the FEN after e5');
kkc_test_equal($e5['san'], 'e5', 'server derives SAN for e5');

$fen = $start;
foreach ([['e2','e4'],['e7','e5'],['g1','f3'],['b8','c6'],['f1','c4'],['g8','f6']] as [$from, $to]) {
    $fen = kkc_chess_apply_move($fen, $from, $to)['fen'];
}
$castle = kkc_chess_apply_move($fen, 'e1', 'g1');
kkc_test_equal($castle['san'], 'O-O', 'king-side castling is validated and notated');
kkc_test_equal(str_contains($castle['fen'], ' b kq '), true, 'castling removes the moving side castling rights');

$castleThroughCheck = '5rk1/8/8/8/8/8/8/4K2R w K - 0 1';
kkc_test_illegal($castleThroughCheck, 'e1', 'g1', null, 'castling through an attacked transit square is rejected');

$fen = $start;
foreach ([['e2','e4'],['a7','a6'],['e4','e5'],['d7','d5']] as [$from, $to]) {
    $fen = kkc_chess_apply_move($fen, $from, $to)['fen'];
}
$enPassant = kkc_chess_apply_move($fen, 'e5', 'd6');
kkc_test_equal($enPassant['san'], 'exd6', 'en passant is validated and notated');
kkc_test_equal(isset(kkc_chess_parse_fen($enPassant['fen'])['board']['d5']), false, 'en passant removes the captured pawn');

$fen = $start;
foreach ([['f2','f3'],['e7','e5'],['g2','g4']] as [$from, $to]) {
    $fen = kkc_chess_apply_move($fen, $from, $to)['fen'];
}
$mate = kkc_chess_apply_move($fen, 'd8', 'h4');
kkc_test_equal($mate['san'], 'Qh4#', 'checkmate SAN is generated by the server');
kkc_test_equal($mate['winner'], 'black', 'server decides the checkmate winner');
kkc_test_equal($mate['endReason'], 'checkmate', 'server decides the checkmate reason');
kkc_test_equal($mate['status'], 'finished', 'checkmate finishes the server match');

$promotion = kkc_chess_apply_move('8/P7/8/8/8/8/7k/K7 w - - 0 1', 'a7', 'a8', 'n');
kkc_test_equal(str_starts_with($promotion['san'], 'a8=N'), true, 'underpromotion is supported');
kkc_test_equal(kkc_chess_parse_fen($promotion['fen'])['board']['a8'], 'N', 'underpromotion creates the requested piece');

$ambiguous = kkc_chess_apply_move('7k/8/8/8/8/8/3N3N/4K3 w - - 0 1', 'd2', 'f3');
kkc_test_equal($ambiguous['san'], 'Ndf3', 'SAN disambiguates two pieces that can reach the same square');

$stalemate = kkc_chess_parse_fen('7k/5K2/6Q1/8/8/8/8/8 b - - 0 1');
kkc_test_equal(kkc_chess_in_check($stalemate, 'b'), false, 'stalemate fixture is not check');
kkc_test_equal(count(kkc_chess_legal_moves($stalemate, 'b')), 0, 'stalemate fixture has no legal move');

$insufficient = kkc_chess_parse_fen('7k/8/8/8/8/8/2B5/K7 w - - 0 1');
kkc_test_equal(kkc_chess_insufficient_material($insufficient), true, 'king and bishop versus king is insufficient material');

kkc_test_illegal($start, 'e2', 'e5', null, 'an impossible pawn jump is rejected');
kkc_test_illegal('4r1k1/8/8/8/8/8/4R3/4K3 w - - 0 1', 'e2', 'd2', null, 'a move exposing the moving king is rejected');

fwrite(STDOUT, "Kush Kings Chess authoritative rule tests passed.\n");
